### ISSUE TITLE
Program received signal SIGPIPE, Broken pipe.

### ISSUE THREAD

**Issue by yulis** [ARMmbed/mbed-client-linux-example#23]
Target: linux-native
Platform: armhf
Board: RaspberryPI 2 Model B
Distro: Raspbian Jessie
Firewall: down
Git rev.: 93d6967bcf5b1ea18777ce3c573e53641845c770
----------------------------------------
#### Socket mode M2MInterface::TCP
(gdb) run
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x76ccf450 (LWP 10674)]
Endpoint Name : 1a409ff7-84fe-4c79-a936-a8cb49f99383

Interface created
register object created
Device object created !!
Registering endpoint

Program received signal SIGPIPE, Broken pipe.
0x76fa146c in sendto () at ../sysdeps/unix/syscall-template.S:81
81	../sysdeps/unix/syscall-template.S: No such file or directory.
```
(gdb) where
```
#0  0x76fa146c in sendto () at ../sysdeps/unix/syscall-template.S:81
#1  0x0003b40c in M2MConnectionHandlerPimpl::send_to_socket (this=<optimized out>, buf=<optimized out>, len=<optimized out>)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-linux/source/m2mconnectionhandlerpimpl.cpp:210
#2  0x0003e1ac in mbedtls_ssl_flush_output (ssl=0x88fc8) at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_tls.c:2452
#3  0x0003e8cc in mbedtls_ssl_write_record (ssl=ssl@entry=0x88fc8)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_tls.c:2855
#4  0x000570b8 in ssl_write_client_hello (ssl=ssl@entry=0x88fc8)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_cli.c:1038
#5  0x00057a0c in mbedtls_ssl_handshake_client_step (ssl=0x88fc8)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_cli.c:3298
#6  0x00041428 in mbedtls_ssl_handshake_step (ssl=0x88fc8) at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_tls.c:6256
#7  0x00041484 in mbedtls_ssl_handshake (ssl=0x88fc8) at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_tls.c:6280
#8  0x0003c81c in M2MConnectionSecurityPimpl::connect (this=0x88f08, connHandler=0x89b50)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-mbedtls/source/m2mconnectionsecuritypimpl.cpp:235
#9  0x0003c1a4 in M2MConnectionSecurity::connect (this=<optimized out>, connHandler=<optimized out>)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-mbedtls/source/m2mconnectionsecurity.cpp:52
#10 0x0003b8bc in M2MConnectionHandlerPimpl::resolve_server_address (this=0x89b60, server_address=..., server_port=<optimized out>, 
    server_type=server_type@entry=M2MConnectionObserver::LWM2MServer, security=0x8a408)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-linux/source/m2mconnectionhandlerpimpl.cpp:177
#11 0x0003b2a0 in M2MConnectionHandler::resolve_server_address (this=<optimized out>, server_address=..., server_port=server_port@entry=5684, 
    server_type=server_type@entry=M2MConnectionObserver::LWM2MServer, security=security@entry=0x8a408)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-linux/source/m2mconnectionhandler.cpp:51
#12 0x0002a998 in M2MInterfaceImpl::state_register (this=0x889c8, data=<optimized out>)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client/source/m2minterfaceimpl.cpp:523
#13 0x00029d28 in M2MInterfaceImpl::state_engine (this=0x889c8)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client/source/m2minterfaceimpl.cpp:732
#14 0x0002a6a0 in M2MInterfaceImpl::register_object (this=0x889c8, security=0x8a408, object_list=...)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client/source/m2minterfaceimpl.cpp:162
#15 0x00025668 in MbedClient::test_register (this=this@entry=0x7efff380) at /home/yulis/mbed/mbed-client-linux-example/source/main.cpp:205
#16 0x00023fac in main () at /home/yulis/mbed/mbed-client-linux-example/source/main.cpp:389
```

#### Socket mode M2MInterface::UDP
(gdb) run
```
Starting program: /home/yulis/mbed/mbed-client-linux-example/build/linux-native/source/mbed-client-linux-example 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x76ccf450 (LWP 10862)]
Endpoint Name : 1a409ff7-84fe-4c79-a936-a8cb49f99383

Interface created
register object created
Device object created !!
Registering endpoint
[New Thread 0x76468450 (LWP 10863)]
[New Thread 0x75c68450 (LWP 10864)]
[Thread 0x76ccf450 (LWP 10862) exited]
...
[Thread 0x76ccf450 (LWP 10921) exited]

Error occured  : M2MInterface::NetworkError

0x76fa1188 in recvfrom () at ../sysdeps/unix/syscall-template.S:81
81	../sysdeps/unix/syscall-template.S: No such file or directory.
```
(gdb) where
```
#0  0x76fa1188 in recvfrom () at ../sysdeps/unix/syscall-template.S:81
#1  0x0003b43c in M2MConnectionHandlerPimpl::receive_from_socket (this=<optimized out>, buf=<optimized out>, len=<optimized out>)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-linux/source/m2mconnectionhandlerpimpl.cpp:217
#2  0x0003f528 in mbedtls_ssl_fetch_input (ssl=ssl@entry=0x88fc8, nb_want=<optimized out>)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_tls.c:2323
#3  0x00042208 in mbedtls_ssl_read_record (ssl=ssl@entry=0x88fc8)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_tls.c:3753
#4  0x00057a3c in ssl_parse_server_hello (ssl=0x88fc8) at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_cli.c:1400
#5  mbedtls_ssl_handshake_client_step (ssl=0x88fc8) at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_cli.c:3309
#6  0x00041428 in mbedtls_ssl_handshake_step (ssl=0x88fc8) at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_tls.c:6256
#7  0x00041484 in mbedtls_ssl_handshake (ssl=0x88fc8) at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbedtls/source/ssl_tls.c:6280
#8  0x0003c81c in M2MConnectionSecurityPimpl::connect (this=0x88f08, connHandler=0x89b50)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-mbedtls/source/m2mconnectionsecuritypimpl.cpp:235
#9  0x0003c1a4 in M2MConnectionSecurity::connect (this=<optimized out>, connHandler=<optimized out>)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-mbedtls/source/m2mconnectionsecurity.cpp:52
#10 0x0003b8bc in M2MConnectionHandlerPimpl::resolve_server_address (this=0x89b60, server_address=..., server_port=<optimized out>, 
    server_type=server_type@entry=M2MConnectionObserver::LWM2MServer, security=0x8a408)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-linux/source/m2mconnectionhandlerpimpl.cpp:177
#11 0x0003b2a0 in M2MConnectionHandler::resolve_server_address (this=<optimized out>, server_address=..., server_port=server_port@entry=5684, 
    server_type=server_type@entry=M2MConnectionObserver::LWM2MServer, security=security@entry=0x8a408)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client-linux/source/m2mconnectionhandler.cpp:51
#12 0x0002a998 in M2MInterfaceImpl::state_register (this=0x889c8, data=<optimized out>)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client/source/m2minterfaceimpl.cpp:523
#13 0x00029d28 in M2MInterfaceImpl::state_engine (this=0x889c8)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client/source/m2minterfaceimpl.cpp:732
#14 0x0002a6a0 in M2MInterfaceImpl::register_object (this=0x889c8, security=0x8a408, object_list=...)
    at /home/yulis/mbed/mbed-client-linux-example/yotta_modules/mbed-client/source/m2minterfaceimpl.cpp:162
#15 0x00025668 in MbedClient::test_register (this=this@entry=0x7efff2a0) at /home/yulis/mbed/mbed-client-linux-example/source/main.cpp:205
#16 0x00023fac in main () at /home/yulis/mbed/mbed-client-linux-example/source/main.cpp:388
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-463

**Comment by yulis** [comment]
Sorry, it was network issue. Works in another network. Please close it
